#!/bin/sh

yume -ex \
  -la 'echo $NP points, $NF faces' -la "# points:" -la NP -iv 11 \
  -la 'echo $NP points, $NF faces' -la "# faces:"  -la NF -iv 11 \
  -bu -la 'test-AA2 visualize' './test-autoAdder2d.py vis $NP $NF' \
      -la 'test-AA2 radius check' './test-autoAdder2d.py value $NP $NF' \
  -bu -la 'test-AA2 time, no cache' './test-autoAdder2d.py time  $NP $NF' \
      -la 'test-AA2 time, with cache' './test-autoAdder2d.py cache $NP $NF'
